### ISSUE TITLE
Addon Manager Support

### ISSUE THREAD

**Issue by kennywasafk** [TylerR909/Talented#4]
Hey! Just wanted to mention that the way it's set up now, Talaned's github page doesn't work with third-party addon managers like Cursebreaker. If you have the time, I would appreciate if you could possibly work in packaged releases? Would be handy to grab the addon directly from here rather than some website like cf or wowi. 

Thanks in advance!

**Comment by Gogo1951** [comment]
Hey @TylerR909,

Happy to show you how to set up BigWigs Packager. It'll take 5 minutes. (=

**Comment by TylerR909** [comment]
Hey y'all. This addon's functionality (Saving & swapping talent builds) is now baked into the default Dragonflight UI. I'm going to archive this repo.
